name: Daily Summary

on:
  schedule:
    - cron: '59 20 * * *'  # 23:59 EET (UTC+3 → UTC 20:59)
  workflow_dispatch:  # Manual trigger

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run daily summary
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        DAILY_ARCHIVE_DB: ${{ secrets.DAILY_ARCHIVE_DB }}
      run: python daily-summary.py
